// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"Plugin used to set basic parameters.","parameters":{"cacheLimit":"20","screenWidth":"960","screenHeight":"540","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"MadeWithMv","status":false,"description":"Show a Splash Screen \"Made with MV\" and/or a Custom Splash Screen before going to main screen.","parameters":{"Show Made With MV":"true","Made with MV Image":"MadeWithMv","Show Custom Splash":"false","Custom Image":"","Fade Out Time":"120","Fade In Time":"120","Wait Time":"160"}},
{"name":"SkipTitle_sx","status":true,"description":"跳过标题画面","parameters":{}},
{"name":"SaveScreen_sx","status":true,"description":"存读档界面修改","parameters":{}},
{"name":"ChainCommand","status":true,"description":"Everyone loves quicktime events.","parameters":{"---Configuration---":"","Valid Keys":"up down left right ok cancel","Default Switch ID":"1","Default Time Given":"360","Time Per Key":"30","Exit Pause Time":"45","---Sound Effects----":"","Keypress SFX":"Cursor2","Success SFX":"Heal3","Error SFX":"Blind","---Timer Bar----":"","Bar BG X Position":"285","Bar BG Y Position":"245","Meter X Shift":"5","Meter Y Shift":"5","Meter Width":"236","Meter Height":"7","---Buttons----":"","Button X Shift":"0","Button Y Shift":"0","Button Width":"31","Button Height":"31","Button Spacing":"15","---Cursor----":"","Cursor X Shift":"5","Cursor Y Shift":"40","---SFX Customization---":"**","Keypress Volume":"100","Keypress Pitch":"100","Keypress Pan":"0","Success Volume":"100","Success Pitch":"100","Success Pan":"0","Error Volume":"100","Error Pitch":"100","Error Pan":"0","":""}}
];
